# Generated by Django 3.1.6 on 2021-08-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210831_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='at_sensorsandlabels',
            name='of_availability',
        ),
    ]
