# Generated by Django 3.1.6 on 2021-08-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_at_sensorsandlabels_of_availability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='At_sensorsandlabels',
            new_name='Datchiki_i_iteketki',
        ),
        migrations.RenameModel(
            old_name='At_systems',
            new_name='ProtivoKrazhSystemy',
        ),
        migrations.CreateModel(
            name='Zashita_stelazhey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('interface', models.CharField(max_length=255, verbose_name='Интерфейс')),
                ('alarm_indication', models.CharField(max_length=255, verbose_name='Индикация тревоги')),
                ('manufacturer_country', models.CharField(max_length=255, verbose_name='Страна производитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schetchiki_posetitelei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('dimensions', models.CharField(max_length=255, verbose_name='Габариты')),
                ('counting_zone', models.CharField(max_length=255, verbose_name='Зона подсчета')),
                ('audible_indication_of_overlaps', models.BooleanField(default=False, verbose_name='Звуковая индикация перекрытий')),
                ('monitoring_of_emergency_situations', models.CharField(max_length=255, verbose_name='Контроль внештатных ситуаций')),
                ('power', models.CharField(max_length=255, verbose_name='Питание')),
                ('device_memory', models.CharField(max_length=255, verbose_name='Память устройства')),
                ('counting_mode', models.CharField(max_length=255, verbose_name='Режим подсчета')),
                ('light_indication_of_passages', models.BooleanField(default=False, verbose_name='Световая индикация проходов')),
                ('setting_up_method', models.CharField(max_length=255, verbose_name='Способ настройки')),
                ('data_transfer_method', models.CharField(max_length=255, verbose_name='Способ передачи данных')),
                ('data_storage', models.CharField(max_length=255, verbose_name='Хранение данных')),
                ('warranty', models.CharField(max_length=255, verbose_name='Гарантия и сервисное обслуживание')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kluchi_siemniki_i_deactivatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gotovye_komplekty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('main_params', models.CharField(max_length=1000, verbose_name='Основные')),
                ('equipment', models.CharField(max_length=1000, verbose_name='Комплектация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Electronnye_cenniki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cifrovaya_avtomatizacia_dlya_biznesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
