# Generated by Django 3.1.7 on 2021-09-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210831_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schetchiki_posetitelei',
            name='audible_indication_of_overlaps',
            field=models.CharField(max_length=255, verbose_name='Звуковая индикация перекрытий'),
        ),
        migrations.AlterField(
            model_name='schetchiki_posetitelei',
            name='light_indication_of_passages',
            field=models.CharField(max_length=255, verbose_name='Световая индикация проходов'),
        ),
    ]
