# Generated by Django 3.1.7 on 2021-09-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210902_0853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProtivoKrazhSystemy',
            new_name='Anti_theft_systems',
        ),
    ]
