# Generated by Django 3.1.7 on 2021-09-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210903_0233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datchiki_i_iteketki',
            new_name='Anti_theft_sensors_and_labels',
        ),
    ]
