# Generated by Django 3.1.7 on 2021-09-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210904_0035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kluchi_siemniki_i_deactivatory',
            new_name='Key_pullers_and_deactivators',
        ),
    ]
