# Generated by Django 3.1.7 on 2021-09-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210904_0039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gotovye_komplekty',
            new_name='Ready_made_kits',
        ),
    ]
