# Generated by Django 3.1.7 on 2021-09-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210904_0041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Electronnye_cenniki',
            new_name='Digital_automation',
        ),
        migrations.RenameModel(
            old_name='Cifrovaya_avtomatizacia_dlya_biznesa',
            new_name='Electronic_shelf_labels',
        ),
        migrations.RenameModel(
            old_name='Zashita_stelazhey',
            new_name='Shelving_protection',
        ),
        migrations.RenameModel(
            old_name='Schetchiki_posetitelei',
            new_name='Visitor_counter',
        ),
    ]
